name: Node.js CD

on:
  workflow_run:
    workflows: ["Node.js CI"]  # Match the exact CI workflow name
    types:
      - completed    

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Ensures CD runs only if CI is successful
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_DEPLOY_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
