name: Node.js CI

on:
  push:
    branches: [ "**" ]  # Matches all branches
  pull_request:
    branches: [ "**" ]  # Runs on PRs from any branch
    
env:
  NODE_VERSION: 20

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone GitHub repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci  # Faster and ensures clean installation than npm install

    - name: Start the App
      run: npm start

    - name: Wait for App to Start
      run: npx wait-on http://localhost:8082 --timeout 30000 || (echo "App failed to start"; cat app.log; exit 1)

    - name: Install Playwright Browsers
      run: npx playwright install 

    - name: Display SoftUni Username
      run: |
        echo "SoftUni Username: yamacheva"

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Run UI Tests
      run: npm run test:ui 
