name: Node.js CI

on:
  push:
    branches: [ "junior-dev" ]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 20

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone GitHub repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Start the App
      run: npm start &

    - name: Wait for App to Start
      run: |
        for i in {1..30}; do
          if curl --silent --head --fail http://localhost:8082; then
            echo "App is running!"
            exit 0
          fi
          echo "Waiting for app..."
          sleep 2
        done
        echo "App did not start in time"
        exit 1

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps > /dev/null || exit 1

    - name: Run Unit Tests
      run: npm run test:unit

    - name: Run UI Tests
      run: npm run test:ui > /dev/null 2>&1
