name: Node.js CD

on:
  push:
    branches: [ "main" ]

jobs:
  check_ci_status:
    runs-on: ubuntu-latest
    steps:
      - name: CI Status Check
        run: echo "Checking CI completion before deployment"

  deploy:
    runs-on: ubuntu-latest
    needs: check_ci_status
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Backend to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_BACKEND_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true